# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(602, 247)
        self.verticalLayout = QtWidgets.QVBoxLayout(Player)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.player_widget = QtWidgets.QWidget(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player_widget.sizePolicy().hasHeightForWidth())
        self.player_widget.setSizePolicy(sizePolicy)
        self.player_widget.setObjectName("player_widget")
        self.verticalLayout.addWidget(self.player_widget)
        self.control_bar = QtWidgets.QWidget(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_bar.sizePolicy().hasHeightForWidth())
        self.control_bar.setSizePolicy(sizePolicy)
        self.control_bar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.control_bar.setObjectName("control_bar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.control_bar)
        self.gridLayout_2.setContentsMargins(4, 0, 4, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_divider = QtWidgets.QLabel(self.control_bar)
        self.lbl_divider.setObjectName("lbl_divider")
        self.gridLayout_2.addWidget(self.lbl_divider, 0, 1, 1, 1)
        self.btn_prev = QtWidgets.QPushButton(self.control_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev.sizePolicy().hasHeightForWidth())
        self.btn_prev.setSizePolicy(sizePolicy)
        self.btn_prev.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btn_prev.setFont(font)
        self.btn_prev.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_prev.setObjectName("btn_prev")
        self.gridLayout_2.addWidget(self.btn_prev, 1, 3, 1, 1)
        self.slider_progress = QtWidgets.QSlider(self.control_bar)
        self.slider_progress.setMinimumSize(QtCore.QSize(100, 0))
        self.slider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_progress.setObjectName("slider_progress")
        self.gridLayout_2.addWidget(self.slider_progress, 0, 3, 1, 8)
        self.lbl_current_time = QtWidgets.QLabel(self.control_bar)
        self.lbl_current_time.setText("")
        self.lbl_current_time.setObjectName("lbl_current_time")
        self.gridLayout_2.addWidget(self.lbl_current_time, 0, 0, 1, 1)
        self.lbl_total_time = QtWidgets.QLabel(self.control_bar)
        self.lbl_total_time.setText("")
        self.lbl_total_time.setObjectName("lbl_total_time")
        self.gridLayout_2.addWidget(self.lbl_total_time, 0, 2, 1, 1)
        self.slider_volume = QtWidgets.QSlider(self.control_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_volume.sizePolicy().hasHeightForWidth())
        self.slider_volume.setSizePolicy(sizePolicy)
        self.slider_volume.setMaximum(100)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setInvertedAppearance(False)
        self.slider_volume.setObjectName("slider_volume")
        self.gridLayout_2.addWidget(self.slider_volume, 1, 9, 1, 1)
        self.btn_next = QtWidgets.QPushButton(self.control_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btn_next.setFont(font)
        self.btn_next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout_2.addWidget(self.btn_next, 1, 4, 1, 1)
        self.video_tracks = QtWidgets.QComboBox(self.control_bar)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.video_tracks.setFont(font)
        self.video_tracks.setObjectName("video_tracks")
        self.gridLayout_2.addWidget(self.video_tracks, 1, 5, 1, 1)
        self.audio_tracks = QtWidgets.QComboBox(self.control_bar)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.audio_tracks.setFont(font)
        self.audio_tracks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.audio_tracks.setObjectName("audio_tracks")
        self.gridLayout_2.addWidget(self.audio_tracks, 1, 6, 1, 1)
        self.sub_tracks = QtWidgets.QComboBox(self.control_bar)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.sub_tracks.setFont(font)
        self.sub_tracks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sub_tracks.setObjectName("sub_tracks")
        self.gridLayout_2.addWidget(self.sub_tracks, 1, 7, 1, 1)
        self.btn_play = QtWidgets.QPushButton(self.control_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btn_play.setFont(font)
        self.btn_play.setObjectName("btn_play")
        self.gridLayout_2.addWidget(self.btn_play, 1, 0, 1, 3)
        self.btn_playlist = QtWidgets.QPushButton(self.control_bar)
        self.btn_playlist.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btn_playlist.setFont(font)
        self.btn_playlist.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_playlist.setObjectName("btn_playlist")
        self.gridLayout_2.addWidget(self.btn_playlist, 1, 10, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 8, 1, 1)
        self.verticalLayout.addWidget(self.control_bar)
        self.playlist = ListView(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist.sizePolicy().hasHeightForWidth())
        self.playlist.setSizePolicy(sizePolicy)
        self.playlist.setObjectName("playlist")
        self.verticalLayout.addWidget(self.playlist)

        self.retranslateUi(Player)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "Form"))
        self.lbl_divider.setText(_translate("Player", "/"))
        self.btn_prev.setText(_translate("Player", "<"))
        self.btn_next.setText(_translate("Player", ">"))
        self.btn_play.setText(_translate("Player", "pp"))
        self.btn_playlist.setText(_translate("Player", "v"))

from browserlist import ListView
